[package]
name = "splat"
version = "0.1.0"
edition = "2021"
default-run = "splat"

[[bin]]
name = "showcase"

[dependencies]
anyhow = "1.0.75"
crossterm = "0.27.0"
log = "0.4.20"
spin_sleep = "1.1.1"
